// Frontend/src/App.svelte
<script>
export let settings;
import Logs from './Logs.svelte';
import TaskManager from './TaskManager.svelte';
import Plugins from './Plugins.svelte';	
import Settings from './Settings.svelte';
import { onMount } from 'svelte';

let menu = [		
	{ name: 'tasks', title: 'Задачи', component: TaskManager},
	{ name: 'logs', title: 'Логи', component: Logs},
	{ name: 'plugins', title: 'Плагины', component: Plugins },		
	{ name: 'settings', title: 'Настройки', component: Settings},
]
let currentTab = menu[0];

$: isMenuDisabled = (item) => currentTab.name === item.name ? 'active' : ''
const setMenu = (item) => {
	document.location.hash = item.name;
	currentTab = item;
}

const initialize = async() => {
	const hash = document.location.hash;
	if (!hash) return;
	const needed = menu.find(x => `#${x.name}` === hash);
	if (needed) setMenu(needed);
}

onMount(initialize);	
</script>

<main class="container">

	<nav class="navbar navbar-light">
	<div class="navbar-brand">{settings.appName}</div>
	<div id="navbarNavAltMarkup">
		{#each menu as item}
			<a class="nav-item nav-link {isMenuDisabled(item)}" on:click="{() => setMenu(item)}" href={`#${item.name}`}>{item.title}</a>
		{/each}
	</div>
	</nav>

	<svelte:component this={currentTab.component} settings={settings}/>
</main>

<style>
	.navbar {
		background-color: #e3f2fd;		
	}

	.navbar-brand {
		color: darkblue;
	}

	main {
		padding: 1em;
		margin: 0 auto;
	}

	.active {
		text-decoration: underline;
	}

	#navbarNavAltMarkup {
		display: flex;
		flex-direction: row;
		/* background: blue; */
	}
</style>

// Frontend_v2/src/Components/App.tsx
import { Settings } from '../types';
import { FC, useEffect, useMemo, useState } from 'preact/compat';
import { cx } from '../utils';
import HealthCheck from './HealthCheck';
import Logs from '../Pages/Logs';
import Plugins from '../Pages/Plugins';
import SettingsPage from '../Pages/Settings';
import TaskManager from '../Pages/TaskManager';

interface MenuItem {
  name: string,
  title: string,
  component: () => JSX.Element
}

const menu : MenuItem[] = [
  { name: 'tasks', title: 'Задачи', component: () => <TaskManager />},
  { name: 'logs', title: 'Логи', component: () => <Logs />},
  { name: 'plugins', title: 'Плагины', component: () => <Plugins /> },
  { name: 'settings', title: 'Настройки', component: () => <SettingsPage />},
]

interface AppProps {
  settings: Settings
}

export const App : FC<AppProps> = (props) => {
  const { settings } = props;

  const [activeMenu, setActiveMenu] = useState<MenuItem>(menu[0]);
  const component = useMemo(() => activeMenu.component(), [activeMenu]);

  const setMenu = (item: MenuItem) => (ev: MouseEvent) => {
    setActiveMenu(item);
  };

  useEffect(() => {
    const hash = document.location.hash;
    if (!hash) return;
    const needed = menu.find(x => `#${x.name}` === hash);
    if (needed) setActiveMenu(needed);
  }, []);

  return <>
    <main className="container">

      <nav className="navbar navbar-light mb-4">
        <div className="navbar-brand">
          <HealthCheck />
          <span className="ml-3">{settings.appName}</span>
        </div>
        <div id="navbarNavAltMarkup">
          {menu.map((item) => (
            <a key={item.name}
               href={`#${item.name}`}
               className={cx("nav-item nav-link", {active: activeMenu.name === item.name})}
              onClick={setMenu(item)}>
              {item.title}
            </a>
          ))}
        </div>
      </nav>

      {component}
    </main>
  </>
}
export default App;
