// Frontend/src/Settings.svelte
<script>
export let settings;

const shutdownClass = settings.isService ? 'disabled' : '';
const shutdownTitle = settings.isService ? 'Приложение запущено как служба и не может быть остановлено отсюда!' : ''
const shutdownClick = async() => {
    if (settings.isService) return;
    const res = await fetch(settings.apiUrl + '/shutdown', { method: 'DELETE'}).then(x => x.json());
    alert(res.Message);
}


const reloadClick = async() => {
    const res = await fetch(settings.apiUrl + '/reload', { method: 'GET'}).then(x => x.json());
    alert(res.Message);
}
</script>

<style>
</style>

<div class="row mt-4">
    <div class="col-12">

    <button class="btn btn-danger {shutdownClass}" title="{shutdownTitle}" on:click="{shutdownClick}">Завершить приложение</button>
    <button class="btn btn-warning" on:click="{reloadClick}">Перезагрузить конфигурацию</button>

    </div>
</div>

// Frontend_v2/src/Pages/Settings.tsx
import { useState } from 'preact/compat';
import Alert, { AlertProps } from '../Components/Alert';
import { wait } from '../utils';
import { makeReload, makeShutdown} from '../api';
import { BootstrapStyle } from '../types';
import { SystemResponse } from '../api/types';


const Settings = () => {

  const [alert, setAlert] = useState<AlertProps|undefined>();

  const doAction = async(action: () => Promise<SystemResponse>, type: BootstrapStyle, hideDelay: number) => {
    const data = await action();
    setAlert({type, message: data.Message});
    await wait(hideDelay).then(() => setAlert(undefined));
  }

  const shutdownClick = () => doAction(makeShutdown, 'danger', 2000);
  const reloadClick = () => doAction(makeReload, 'info', 2000);

  return <div>

    {alert && <Alert {...alert} />}

    <button className="btn btn-danger mr-3" title="{shutdownTitle}" disabled={false} onClick={shutdownClick}>
      Завершить приложение
    </button>
    <button className="btn btn-warning" onClick={reloadClick}>
      Перезагрузить конфигурацию
    </button>

  </div>
}

export default Settings;
